apiVersion: v1
kind: Service
metadata:
  name: comments-srv-dev
spec:
  type: NodePort
  selector:
    # This is the pod name described in "template" inside comments-depl.yaml (metadata > labels > app:comments)
    app: comments
  ports:
    - name: comments
      protocol: TCP
      # In general, port and targetPort will be identical
      # Node port ("virtual machine"/"pod" used port when service is called)
      port: 4001
      # Port used whe pod is called by the service
      targetPort: 4001
